project:
  name: OpenWaste-HR
  api_stage: prototype_api_wrapper
  version: v1

inference:
  single_image_config_path: ml/configs/inference_pipeline.yaml

api:
  allowed_image_extensions:
    - .jpg
    - .jpeg
    - .png

  max_image_path_length: 500

outputs:
  output_metrics_dir: ml/outputs/metrics
  output_response_json: best_pretrained_safe_prototype_api_response_v1.json
  output_response_markdown: best_pretrained_safe_prototype_api_response_v1.md
# active checkpoint: ml/outputs/checkpoints/pretrained_trashnet_v1/pretrained_trashnet_v1_best.pt

# active_policy: best_pretrained_safe_policy_v1


active_policy:
  name: best_pretrained_safe_policy_v1
  model: pretrained_trashnet_v1
  checkpoint: ml/outputs/checkpoints/pretrained_trashnet_v1/pretrained_trashnet_v1_best.pt
  fine_confidence_threshold: 0.995
  coarse_confidence_threshold: 0.8
  coarse_margin_threshold: 0.15
  minimum_confidence_for_coarse: 0.9
